spring:
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
  profiles:
    default: local
    include: secret
  web:
    resources:
      static-locations:
        classpath:/static/
      add-mappings: true
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true